url: "https://azlen.me"
baseurl: ""
plugins:
  - jekyll-pandoc
  - jekyll-twitter-plugin
  - jekyll-mentions
  - jekyll-scholar
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-resize
  - jekyll-timeago

markdown: Pandoc
pandoc:
  extensions:
    - section-divs
    - from: 'markdown+tex_math_single_backslash'
    - filter: 'pandoc-sidenote'

collections:
  pages:
    output: true
    permalink: /:path/

exclude:
  - _pages/.obsidian
  - _pages/_templates
  - _pages/drafts
  - _pages/archive
  - _pages/.vault-stats
  - Gemfile
  - Gemfile.lock
  - tufte-pandoc-jekyll.gemspec
  - run
  - TODO
  - publish.sh

include:
  - _redirects
  - _pages/\~
  - _pages/~/
  - _pages/~/*
  - _pages/\~/*

jekyll-mentions:
  base_url: https://twitter.com

last-modified-at:
  date-format: '%Y-%m-%d'

jekyll_timeago:
  depth: 1